create table if not exists public.visits (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) between 1 and 200),
    phone text not null check (char_length(trim(phone)) between 1 and 40),
    email text not null check (char_length(trim(email)) between 3 and 320),
    visit_date date,
    message text not null default '' check (char_length(message) <= 5000),
    status text not null default 'New'
        check (status in ('New', 'Contacted', 'Visited', 'Closed')),
    created_at timestamptz not null default now()
);

alter table public.visits
    drop constraint if exists visits_phone_format;
alter table public.visits
    add constraint visits_phone_format check (phone ~ '^\+91[0-9]{10}$');

create table if not exists public.admin_users (
    user_id uuid primary key references auth.users (id) on delete cascade,
    created_at timestamptz not null default now()
);

alter table public.visits enable row level security;
alter table public.admin_users enable row level security;

revoke all on public.visits from anon, authenticated;
revoke all on public.admin_users from anon, authenticated;

grant insert (name, phone, email, visit_date, message, status)
    on public.visits to anon;
grant usage on sequence public.visits_id_seq to anon;
grant select, insert, update, delete on public.visits to authenticated;
grant usage, select on sequence public.visits_id_seq to authenticated;
grant select on public.admin_users to authenticated;

drop policy if exists "Public can submit visit requests" on public.visits;
create policy "Public can submit visit requests"
    on public.visits for insert to anon, authenticated
    with check (status = 'New');

drop policy if exists "Admins can read visit requests" on public.visits;
create policy "Admins can read visit requests"
    on public.visits for select to authenticated
    using (
        exists (
            select 1 from public.admin_users
            where user_id = (select auth.uid())
        )
    );

drop policy if exists "Admins can update visit requests" on public.visits;
create policy "Admins can update visit requests"
    on public.visits for update to authenticated
    using (
        exists (
            select 1 from public.admin_users
            where user_id = (select auth.uid())
        )
    )
    with check (
        exists (
            select 1 from public.admin_users
            where user_id = (select auth.uid())
        )
    );

drop policy if exists "Admins can delete visit requests" on public.visits;
create policy "Admins can delete visit requests"
    on public.visits for delete to authenticated
    using (
        exists (
            select 1 from public.admin_users
            where user_id = (select auth.uid())
        )
    );

drop policy if exists "Admins can read their own allowlist entry" on public.admin_users;
create policy "Admins can read their own allowlist entry"
    on public.admin_users for select to authenticated
    using (user_id = (select auth.uid()));